apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-demo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/neravr/idp-gitops
    targetRevision: HEAD
    path: manifests/idp-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: idp-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true